Tweaks to test_hector.sh, check tgav constraint
JGCRI/hector pull request #558
Opened 2022-01-28 14:26 UTC by bpbond

Checked that the tgav constraint is exercised in the test script, and made it more flexible (now runs all INI files found in `./inst/input` rather than hard-coded names).

2022-01-31 13:50 UTC, kdorheim commented
@bpbond is this ready for review or wait until the tgav constraint code is re-implemented?

2022-01-31 14:44 UTC, bpbond commented
@kdorheim Please wait until I do that.

2022-03-13 11:28 UTC, bpbond commented
@kdorheim Ready for your review

2022-03-16 11:28 UTC, kdorheim commented on src/temperature_component.cpp
> +        temp[tstep] = tgav_constrain.get( runToDate );
Add a comment here describing what is going on in `temp_landair ` and `temp_sst`.

2022-03-16 11:36 UTC, kdorheim approved these changes
Looks great Ben! Would it be useful to have the capability for R hector users to implement the constraint through in R or should it remain a feature to implement via the ini file?

2022-03-16 18:51 UTC, bpbond commented
Wait why didn't pushing 314b628 trigger tests? 😕

2022-03-16 18:52 UTC, bpbond commented
@kdorheim Could you remove your approval on this PR? I don't understand why tests aren't running.

2022-03-17 20:52 UTC, kdorheim requested changes
does this trigger the tests?

2022-03-18 15:04 UTC, bpbond commented
@kdorheim Thanks! Not sure what happened, but yes tests did rerun. Just pushed a commit I hope will fix the test failure and then ready to merge from my pov.

2022-03-18 15:47 UTC, bpbond commented
Hurray! Back to you @kdorheim

2022-03-18 18:29 UTC, kdorheim approved these changes
Beautiful! Thanks for adding the R functions!

2022-03-18 18:40 UTC, merged