LP doc edits
JGCRI/hector pull request #599
Opened 2022-03-29 19:11 UTC by leeyap

Hi @kdorheim,

I read through the documentation (everything in the vignette/article folder) and made some edits - mostly spelling checks, but also some clarity/flow edits and a few minor code tweaks/clean ups. 

A few things:
- In `multiple-biomes.Rmd`,  I was getting a "core is auto resetting" warning even with resetting it manually after splitting up a biome (line 47, 108ish)
- There is a .cvg file in the directory, I don't think it belongs

In general:
- Do we want there to be a consistent ggplot theme/color scheme across all articles? 
- There were a couple of words where the capitalization was inconsistent across docs, but within articles (e.g. "ini" vs "INI" or "Hector" vs "hector"). I changed some where I noticed, but wasn't nitpicky about it (I can be!)

Let me know if there's anything you'd like me to change, I hope this is useful!

2022-03-30 01:41 UTC, kdorheim requested changes
@leeyap thanks for the careful review, a few minor comments

2022-03-30 01:41 UTC, kdorheim commented on vignettes/articles/Hector-Wider-World.Rmd
> +## Hector Publications {#hector_documentation}
This is a hyperlink used in the manual.Rmd, please also update that call in line 21

2022-03-30 12:39 UTC, leeyap commented on vignettes/articles/AddNewComponent.Rmd
> +Under `core::init()` section add code to create your new component:
Whoops, that was a mistake, thanks!

2022-03-31 16:19 UTC, kdorheim approved these changes

2022-03-31 16:19 UTC, merged