Adjust potential NPP based on vegetation LUC losses (or gains)
JGCRI/hector pull request #639
Opened 2022-10-13 06:28 UTC by bpbond

Per discussion with @dawnlwoodard and @kdorheim yesterday — see #638 

## Changes

This PR adds a new term to our NPP calculation: vegetation losses (or gains) due to LUC change, with the the aim of avoiding double-counting regrowth fluxes. We save the end-of-spinup vegetation C value; keep a running total of LUC emissions from (or gains to) vegetation; and then adjust NPP:
```c++
  npp_luc_adjust = (end_of_spinup_vegc - cum_luc_va) / end_of_spinup_vegc;
  npp = npp * npp_luc_adjust;
```

## Impact (SSP2.45)

![npp_adjust](https://user-images.githubusercontent.com/1956468/195517966-3ba0d69a-14fc-40f6-a8dd-f06109370aaf.png)

![overall](https://user-images.githubusercontent.com/1956468/195517902-8ddf4fba-253e-4741-a103-ba3d3f24e440.png)

```r
> library(hector)
> core <- newcore(system.file("input/hector_ssp245.ini", package = "hector"))
> run(core)
> x <- fetchvars(core, dates = 1750:2300)
> x$which <- "v3_dev"
> [ same with new functionality ]
> y$which <- "This PR"
> z <- rbind(x, y)
> ggplot(z, aes(year, value, color = which)) + facet_wrap(~variable, scales="free") + geom_point() + coord_cartesian(xlim=c(1950, 2030))
```

2022-10-13 17:48 UTC, kdorheim commented
Cool, I am really interested to hear what @dawnlwoodard says since their work identified this problem. 

Something I am slightly confused about though is how the carbon pools are connected with the NPP. 

https://github.com/JGCRI/hector/blob/d1af1b7a1ffa5b90ab6cdbbeb828164c589ab50f/src/simpleNbox-runtime.cpp#L353

Based on my limited understanding of Hector's carbon cycle component it looks like the c pools (veg, detritus, and soil) are updated with luc emissions already right? So does this change now cause a double counting of the luc in these pools? Also does beta not have an effect on NPP anymore?

2022-10-13 17:50 UTC, kdorheim commented
Using the same setup as Ben but focusing on the historical period but including more variables

![image](https://user-images.githubusercontent.com/27299759/195669272-ffde5fd5-e74d-44aa-89bc-5bb889593ed2.png)

2022-10-13 18:47 UTC, bpbond commented
Cool—thanks @kdorheim

2022-10-13 19:46 UTC, bpbond commented
> it looks like the c pools (veg, detritus, and soil) are updated with luc emissions already right? So does this change now cause a double counting of the luc in these pools? Also does beta not have an effect on NPP anymore?

Old sequence:
1. Calculate beta effect
2. Apply beta effect to NPP
3. Allocate NPP to pools and proceed through carbon cycle

New sequence:
1. (Keep track of the running total of vegetation C lost to LUC)
2. Calculate beta effect
3. Calculate LUC effect as NPP0 *  (change of veg_lost_to_luc / preindustrial veg). E.g. if 1% of vegC has been lost to date to LUC, the LUC effect would be 99%
4. Apply beta and LUC effects to NPP: `npp = npp0 * beta_effect * luc_effect` basically
5. Allocate NPP to pools and proceed through carbon cycle

2022-10-13 19:49 UTC, dawnlwoodard commented
Yay!! Thanks @bpbond! I will test this out tomorrow morning and plan to add the regrowth figures here so we can see how much of an impact this has.

@kdorheim Yes the carbon pools are already updated with LUC emissions, but, unlike respiration, NPP does not itself depend on the size of the current carbon pools. It is purely calculated as a function of initial NPP and a CO2 fertilization multiplier. So this PR actually allows NPP to adjust with LUC emissions. Which, logically, should make some sense. If you cut down half of the forest, the NPP in that forest should not be the exact same as before. What we are trying to do here is something like this: 
<img width="613" alt="hector_eq" src="https://user-images.githubusercontent.com/1285408/195693848-189d53ae-88c1-47aa-9ec4-80130e617b82.png">

where if Hector is in equilibrium and then you remove an amount of LUC emissions, Hector's land carbon drops to a new equilibrium. Of course the example I'm showing above doesn't have any nonlinear components, so Hector is not going to look this clean. And to maintain perfect equilibrium you also need to remove those LUC emissions proportional to the current size of each pool, but as Ben pointed out when we discussed this issue, that's not realistically how carbon would move, so we're also not going to do that. 

Also, beta should still affect NPP - this is just an additional multiplier. 

But at first glance this looks promising - as in, it does what we expect of increasing CO2 and dropping the size of the land carbon pools.

2022-10-14 00:03 UTC, ssmithClimate commented
Note that if you cut down half a forest, NPP doesn't necessarily change. It's just a different vegetation type. Any change would be because the new vegetation type has a lower or higher NPP than the old one. It could go either way. You need to look at the data to see which way that might go.

2022-10-14 15:19 UTC, bpbond commented
@ssmithClimate thanks, and right, it definitely can get tricky—NPP _might_ not drop. But even if it didn't, the duplication-of-regrowth issue, along with the pave-the-amazon scenario (cf. #531 ), plus the fact that Hector already runs low compared to historical CO2/temp, all argue for addressing this I think.

2022-10-17 17:48 UTC, dawnlwoodard commented
Okay, so running pulse tests with this is interesting.

If we turn off nonlinear land components (q10 and beta), we get what I would expect in vegetation and detritus, but soil still has an odd amount of regrowth happening and I'm not sure why:
![image](https://user-images.githubusercontent.com/1285408/196246571-e9fc2bfb-457b-4dcd-a397-7871d59b5655.png)

If we don't turn off the nonlinear pieces, things get extra wonky: 
![image](https://user-images.githubusercontent.com/1285408/196247137-ed3dae6d-92b0-4819-a715-160181e4326f.png)

2022-10-17 18:51 UTC, kdorheim commented
Hmmm @dawnlwoodard agreed that the soil C pool dynamics look funky @bpbond any ideas as to where the growth in soil C is coming from?

2022-10-17 20:31 UTC, dawnlwoodard commented
As I'm looking into this further, another piece I don't understand is why the pools each have 2 large drops (in 1800 *and* 1801) rather than just one in 1800 when the pulse happens. 

![image](https://user-images.githubusercontent.com/1285408/196276953-aa64ddee-51d3-42eb-bbae-f1e26e8e1fa8.png)

![image](https://user-images.githubusercontent.com/1285408/196277217-7b913af4-4976-4ffb-840e-23f45f2c12a0.png)

![image](https://user-images.githubusercontent.com/1285408/196277241-16c09519-2eaa-4ea9-b8d6-1f763c12819c.png)

2022-10-18 01:34 UTC, bpbond commented
@dawnlwoodard 

> soil still has an odd amount of regrowth happening 

Probably because we're _not_ taking out the LUC pulse proportionately? I.e., we're still following Hector's default (more realistic, I said to you last week) fractions.

>another piece I don't understand is why the pools each have 2 large drops (in 1800 and 1801) 

I suspect that this is a time-smudge issue: half is being taken out in 1799.5-1800, and half in 1800-1800. But that's not what people will expect...

Seems like I should make the first change, at least, so you have a clean basis for testing.

2022-10-18 01:44 UTC, bpbond commented
@dawnlwoodard Temporarily shifted to proportional LUC losses/gains in 3b40525 ; haven't tested except yes it runs, but should do what you want.

2022-10-18 12:05 UTC, dawnlwoodard commented
Thanks, @bpbond! So running with the changes *and* with nonlinear pieces turned off we would expect to produce a clean drop to a new equilibrium with no regrowth. But instead it now has consistent, small regrowth in every land C pool. It's a small amount, so not *super* concerned, but I am curious what's driving it. With the beta effect off, there's no actual dependence on the atmospheric carbon concentration, so it's not a response to that pool changing. 

![image](https://user-images.githubusercontent.com/1285408/196421782-3490f4b1-5484-4e6d-992b-a4e6a809afc3.png)

With nonlinear back on (below) the jerkiness is fixed but the regrowth is still amplified somewhat (which we would expect). The question is just whether this is too much regrowth or not. Which, as @bpbond and I discussed when we first talked about this, is not necessarily a clear line to draw. My thought is that this is maybe small enough to not worry about *if* we can fix the regrowth that's happening in the purely linear one ^.  Because this amplification doesn't seem like much if that weren't already happening. Mind you, none of what I've said here is necessarily a reason to not merge this in, as long as we can at least explain why that bit of regrowth is happening still in the purely linear version above. Like, less double counting is still an improvement. *But* imho if we're going to make a change this significant (in terms of impact on model results, necessitating recalibration, etc), then it does seem better to get it all the way how we want it.

![image](https://user-images.githubusercontent.com/1285408/196422769-185c7666-7b37-4df6-91c1-cb8eb57a20ff.png)

2022-10-18 12:11 UTC, dawnlwoodard commented
My other thought on this is that before you changed the luc fractions, @bpbond, the soil vs vegetation were not actually behaving in a more realistic way, unless I'm not thinking about this right. Based on what you and I discussed, what we talked about as being more realistic is that the soil should lose relatively less carbon due to LUC emissions, compared to vegetation and detritus. So what you'd expect is the soil carbon pool to drop further over time as it comes back into equilibrium, right? Whereas instead we saw the biggest drop in soil, such that it was regrowing, and vegetation and detritus were the ones dropping further to come into equilibrium. Am I missing something? Is that actually the behavior we'd expect?

2022-10-24 12:12 UTC, dawnlwoodard commented
Sounds good, @bpbond. Let's discuss Wednesday. 

Re: "On the other, as you note, it's a small adjustment: <0.1%. Tough for me to prioritize this." - yes, the remaining effect here is small and alone I agree would not be a priority. *But* the intended default way we'd like to run Hector is of course with feedbacks on, which regrows a larger fraction of the carbon lost, and likely also with LUC fractions fixed, which regrows even more. I'm not sure we can just dismiss that amount of regrowth as insignificant. And it's unclear to me whether the fixes are unrelated or not. But, as I said before, less regrowth is still better. So we could certainly justify letting this be a good start and leaving it at that.

2022-10-26 14:59 UTC, dawnlwoodard commented
@bpbond reminder to circle back to this. Per our discussion, we believe we are pulling too much carbon from all three land C pools relative to new NPP. Possibly an issue with calculations that happen outside of the solver versus fractions that get calculated in the solver.

2022-10-28 13:01 UTC, bpbond commented
@dawnlwoodard OK, I have fixed and merged ( #644 ) ANOTHER bug that your work has uncovered! 👏  The LUC pulse test now matches your spreadsheet I think — see graph in #643 .

@kdorheim This PR now has some significant changes that, combined, definitely affect model behavior:
* Interpolation bugfix
* LUC loss fractions changed to proportional
* NPP adjustment for vegetation LUC losses

![divergence](https://user-images.githubusercontent.com/1956468/198594405-c5224e74-32af-4c16-9362-796f473ecf98.png)

At your convenience, could you take a hard look at the performance of this PR, e.g. by running it through your v3 assessment RMarkdown you showed me yesterday?

2022-10-28 13:07 UTC, bpbond commented
Two other notes before I go offline for a while.

1. The old-new test is currently disabled, just so we can quickly and easily see if everything else passes.
2. What about the LUC fractions?

## LUC fractions

To date Hector has let users set how LUC emissions (uptake) pull from (flow into) veg, detritus, and soil:
```
f_lucv=0.1			; Fraction of land use change flux from vegetation
f_lucd=0.01			; Fraction of land use change flux from detritus (balance from soil)
```

But I'm persuaded by Dawn's argument here: this approach is both _ad hoc_ and dependent on what kind of LUC occurs, and it's simpler and more defensible to just pull proportionately from the three pools. That what was implemented in [3b40525](https://github.com/JGCRI/hector/pull/639/commits/3b4052565f10ef210feba651799c95f827e8fc3e) on a test basis, and I'm proposing we make permanent. Two questions then:
* Does this seem reasonable?
* If we do this, do we rip out the `f_lucv` and `f_lucd` settings entirely? Or let users set them if they want to override the default behavior?

2022-10-28 13:26 UTC, kdorheim commented
@bpbond will do taking a look at it now!

2022-10-28 13:58 UTC, dawnlwoodard commented
@bpbond so exciting!! So glad you figured out what was behind the weird behavior I was seeing and that these tests can help with future diagnosis as well. 

Re: LUC fractions, I think it could be useful to have users be able to override them *especially* if they're biome-specific. Then someone could break out a particular biome that should have specific LUC-related behavior if they want. But if it's going to be a pain to keep them around, may not be worth it.

2022-10-28 15:00 UTC, kdorheim commented
Okay I ran it through the manuscript three calibration/figures we were looking at yesterday. 

Look at how great the Hector v3 with the new luc update fits [co2]!
![image](https://user-images.githubusercontent.com/27299759/198659530-57e0fa51-f82e-4648-964b-617d7f3496c1.png)

The comparison with the other observations GISS temp and GCP are not as good but I am not that concerned. 

![image](https://user-images.githubusercontent.com/27299759/198661819-901506f3-66c1-4aee-99cd-0c0153f7a851.png)
![image](https://user-images.githubusercontent.com/27299759/198662096-9b9fdb26-e4fd-4d56-9a2c-ecc5c5a7a612.png)

2022-10-28 16:35 UTC, dawnlwoodard commented
@kdorheim glad CO2 is fitting better! Also, on these figures, is old luc just Hector v3 without Ben's latest fixes? I guess I'm particularly wondering why old and new luc have such different land sink behavior.

2022-10-28 20:11 UTC, kdorheim commented
@dawnlwoodard so there are two differences in the Hector output, the hand full of Ben's latest commits and also the parameters used. The difference between the land sink is a combination of these two factors. In the plot below I ran the same luc branch but with different parameter combinations and we see the large change in land sink behavior. 

old params 
```
     diff    q10_rh      beta 
1.7263138 0.9330690 0.2890119 
```

new params 

```
     diff    q10_rh      beta 
1.1759621 2.1558709 0.5529147 
```

![image](https://user-images.githubusercontent.com/27299759/198723244-b412c03f-0492-43b8-8f8d-c9307ed93314.png)

2022-10-29 11:50 UTC, bpbond commented
I took an exploratory look at keeping `f_lucv` and `f_lucd` around — see the `luc_option` branch.

Making these fractions biome-specific, and allowing for two different behaviors (default proportional, but user could override on a biome-specific basis), that has to be implemented in two different places (`calc_derivs()` and `stashCValues()`), would introduce a fair amount of complexity. And imho that's not something we need more of at the moment, at least not without a strong reason!

So, my vote would be to remove them entirely, which is what #645 does. We can discuss next week, but if this makes sense, @kdorheim can merge #645 into this PR and then re-evaluate changed from `v3_dev` please.

🙏

2022-10-31 11:59 UTC, kdorheim commented
@bpbond in your figure generated above comparing Hector's outputs could you please include NBP, NPP, and Rh?

2022-10-31 12:21 UTC, bpbond commented
@kdorheim 

![new](https://user-images.githubusercontent.com/1956468/199006450-3e6a40f9-d8b8-4cce-bc01-bc30c108c6e3.png)

2022-10-31 12:27 UTC, kdorheim commented
Thanks Ben I will take a look at the PR in a bit. The terrestrial carbon cycle changes seem large do these changes seem reasonable/along the lines of what you were expecting?

2022-10-31 12:38 UTC, bpbond commented
I don't know. Those NBP lines are pretty distressingly different.

2022-10-31 12:49 UTC, kdorheim commented
Yea... it seems like these changes have made Hector more sensitive to parameter values... What does the output looks like when 
aero = 1
volscl = 1
ECS = 3
NPP0 = 56.2
diff = 1.18 
q10 = 2.16
beta = 0.55

2022-10-31 12:55 UTC, bpbond commented
![new](https://user-images.githubusercontent.com/1956468/199012625-f2f12e8f-875f-4124-8ded-70655ac22234.png)

2022-10-31 13:04 UTC, kdorheim commented
hmmm interesting the developments seemed to have really increased Hector's parameter sensitivity

2022-10-31 15:29 UTC, kdorheim requested changes
@bpbond this is only a partial review but may be relevant to the interpolation devlopment

2022-10-31 15:33 UTC, bpbond commented on inst/input/tables/ssp126_emiss-constraints_rf.csv
> +1745,0,0,0,0,0,0,0,0.025000429,0,34.04999924,0,0,0,0,0,0,0,0,0,0,0,5.299997807,0,0,457.0000025,0,731.4059957,0,277.1470032,0,0,0,0.286266211,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,273.865051
The model starts at 1745 🤷  otherwise no reason

2022-10-31 15:33 UTC, bpbond commented on NAMESPACE
> -export(CO2_CONSTRAIN)
Uh no whoops

2022-10-31 15:33 UTC, bpbond commented on NAMESPACE
> -export(CO2_CONSTRAIN)
Thank you

2022-10-31 15:35 UTC, kdorheim commented on inst/input/tables/ssp126_emiss-constraints_rf.csv
> +1745,0,0,0,0,0,0,0,0.025000429,0,34.04999924,0,0,0,0,0,0,0,0,0,0,0,5.299997807,0,0,457.0000025,0,731.4059957,0,277.1470032,0,0,0,0.286266211,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,273.865051
hahah that is a pretty good reason, I will update hectordata to make sure the input files start at year 1745

2022-11-03 02:09 UTC, closed without merging